# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""A class for encoding in the qubits' encoding"""
__author__ = "HMY"
__date__ = "2023-Jul-13"

import numpy as np
import dataclasses
from dataclasses import dataclass


class evqa(object):
    """
    A general inclusion of parameters the Efficient Variational quantum Approximation algorithom with restriction

    n,N ref parameters.py
    qn (QuantumRegister): the quantum register, default is False, like we need to generate a register
    qc (QuantumCircuit): the quantum circuit, default is False, like we need to generate a register
    allo (int list): allocation of the qubits to each asset, default is the equal allocation
    order (int list): the label order of each asset, default is as above statement in nk
    enco (str): encoding diagram: b: means binary, o: means one hot encoding
    bitRan (np.ndarray): the range of each asset change by 1 increase like for allo is [5,5,5,5,5], then bitRan is [32,32,32,32,32]
    amp (np.ndarray): the amplitude of accuracy

    nk (int list): a list generated by the above information contains the setting of the encoding
    the first (int): the number of asset
    the second (int): the number of the qubits,
    the third (int list): how many qubits for each assets, default is equal divided
    the last (int list): the coefficient we choose for each asset's qubits, the default is empty and means binary
    numBits (np.ndarray): a full size of quantum qubits
    e.g.:
        nk = [4, 8, [2,2,2,2], [0,1,2,3], [[1,2],[1,2],[1,2],[1,2]] ] or nk = [4, 8]
    the asset size is 4, use 8 qubits, for each asset use 2 qubits, and asset label as 0,1,2,3,
    then as to the corresponding, the coefficient of each qubits, 0 asset the first qubit is 1, the second qubits is 2, etc
    """

    def __init__(
        self,
        n: int,
        N: int,
        allo: list = False,
        order: list = False,
        enco: list = False,
    ):
        self.n = n
        self.N = N

        if not allo:
            self.allo = self.equalAllo()
        self.D = np.array([(2 ** self.allo[i] - 1) for i in range(self.n)])
        self.amp = np.array([1 / self.D[i] for i in range(self.n)])

        if not order:
            self.order = self.orderArang()

        if not enco:
            self.encoMe = "binary"
            (
                self.enco,
                self.encoN,
            ) = self.binary()  # encoN is the normalized encoding setup

        self.numBits = np.ones(self.N)
        (
            self.posI,
            self.posQ,
        ) = (
            self.position()
        )  # posI is the position for the internal of qubit, posQ is the position for the whole qubit strings
        self.bitRan = np.array([2 ** self.allo[i] for i in range(self.n)])
        # get the bit blocks weight

    def equalAllo(self) -> list[int]:
        """
        this function tells the default qubits for each assets
        """

        div = int(self.N / self.n)

        if div != self.N / self.n:
            raise Exception("Check the qubit size or number of assets")
        return [div for _ in range(self.n)]

    def orderArang(self):
        """
        this function tells the default asset arrangement
        """
        return [i for i in range(self.n)]

    def binary(self):
        """To generate the binary assignment of coefficient"""
        enco = [[2**j for j in range(self.allo[i])] for i in range(self.n)]
        encoN = [
            [2**j / (2 ** self.allo[i] - 1) for j in range(self.allo[i])]
            for i in range(self.n)
        ]
        return enco, encoN

    def position(self):
        """ "
        generate the qubit positions
        """
        posQ = [
            [j + sum(self.allo[:i]) for j in range(self.allo[i])] for i in range(self.n)
        ]
        posI = [[j for j in range(self.allo[i])] for i in range(self.n)]

        return posI, posQ


@dataclass(init=False)
class enco:
    n: int
    N: int
    allo: list[int]
    posQ: list
    posI: list
    encoN: list

    # only pass the variables recognize, and if parameter not passed ignored
    # if you want to access the attributes after init, use __post_init__
    def __init__(self, **kwargs):
        names = set([f.name for f in dataclasses.fields(self)])
        for k, v in kwargs.items():
            if k in names:
                setattr(self, k, v)
