# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""A digram class for Efficient Variational quantum Approximation algorithom to solve risk parity model"""
__author__ = "HMY"
__date__ = "2023-01-23"

# import sys

# sys.path.insert(0, "/Users/haomuy/Documents/gitea/QAOA")  # for mackbook pro
# sys.path.insert(0, "/Users/apple/Documents/riskparity")  # for mack mini
import numpy as np
from typing import Union, List
from qiskit import QuantumCircuit, QuantumRegister, AncillaRegister
from qiskit_aer import Aer
from qiskit import ClassicalRegister, transpile
from qiskit.circuit.library import QAOAAnsatz


class EVQAA(object):
    """
    A general inclusion of parameters the Efficient Variational quantum Approximation algorithom with restriction

    n,N ref parameters.py
    qn (QuantumRegister): the quantum register, default is False, like we need to generate a register
    qc (QuantumCircuit): the quantum circuit, default is False, like we need to generate a register
    allo (int list): allocation of the qubits to each asset, default is the equal allocation
    order (int list): the label order of each asset, default is as above statement in nk
    enco (str): encoding diagram: b: means binary, o: means one hot encoding
    bitRan (np.ndarray): the range of each asset change by 1 increase like for allo is [5,5,5,5,5], then bitRan is [32,32,32,32,32]
    amp (np.ndarray): the amplitude of accuracy

    nk (int list): a list generated by the above information contains the setting of the encoding
    the first (int): the number of asset
    the second (int): the number of the qubits,
    the third (int list): how many qubits for each assets, default is equal divided
    the last (int list): the coefficient we choose for each asset's qubits, the default is empty and means binary
    numBits (np.ndarray): a full size of quantum qubits
    e.g.:
        nk = [4, 8, [2,2,2,2], [0,1,2,3], [[1,2],[1,2],[1,2],[1,2]] ] or nk = [4, 8]
    the asset size is 4, use 8 qubits, for each asset use 2 qubits, and asset label as 0,1,2,3,
    then as to the corresponding, the coefficient of each qubits, 0 asset the first qubit is 1, the second qubits is 2, etc
    """

    def __init__(
        self,
        n: int,
        N: int,
        allo: list = False,
        order: list = False,
        enco: list = False,
    ):
        self.n = n
        self.N = N

        if not allo:
            self.allo = self.equalAllo()
        self.D = np.array([(2 ** self.allo[i] - 1) for i in range(self.n)])
        self.amp = np.array([1 / self.D[i] for i in range(self.n)])

        if not order:
            self.order = self.orderArang()

        if not enco:
            self.encoMe = "binary"
            (
                self.enco,
                self.encoN,
            ) = self.binary()  # encoN is the normalized encoding setup

        self.numBits = np.ones(self.N)
        (
            self.posI,
            self.posQ,
        ) = (
            self.position()
        )  # posI is the position for the internal of qubit, posQ is the position for the whole qubit strings
        self.bitRan = np.array([2 ** self.allo[i] for i in range(self.n)])
        # get the bit blocks weight

    def equalAllo(self):
        """
        this function tells the default qubits for each assets
        """

        div = int(self.N / self.n)

        if div != self.N / self.n:
            raise Exception("Check the qubit size or number of assets")
        return [div for _ in range(self.n)]

    def orderArang(self):
        """
        this function tells the default asset arrangement
        """
        return [i for i in range(self.n)]

    def binary(self):
        """To generate the binary assignment of coefficient"""
        enco = [[2**j for j in range(self.allo[i])] for i in range(self.n)]
        encoN = [
            [2**j / (2 ** self.allo[i] - 1) for j in range(self.allo[i])]
            for i in range(self.n)
        ]
        return enco, encoN

    def position(self):
        """ "
        generate the qubit positions
        """
        posQ = [
            [j + sum(self.allo[:i]) for j in range(self.allo[i])] for i in range(self.n)
        ]
        posI = [[j for j in range(self.allo[i])] for i in range(self.n)]

        return posI, posQ


def bl2bll(eqv: EVQAA, z: Union[np.ndarray, str]):
    """from a binary string list[] to a [[], ]

    Args:
        eqv (EVQAA): _description_
        z (Union[list, str]): _description_
    """
    new_z = []
    for i in range(len(eqv.posQ)):
        new_z.append([z[i] for i in eqv.posQ[i]])
    return np.array(new_z)


def btx(eqv: EVQAA, z: Union[np.ndarray, str]):
    if type(z) == str:
        pass
    new_z = bl2bll(eqv=eqv, z=z)
    encoN = np.array(eqv.encoN)

    x = np.array([new_z[i] @ encoN[i] for i in range(len(new_z))])

    return x


# @spendtime
def combCircQAOA(
    n: int,
    name: str,
    simulator: Aer,
    p: int,
    initCirc: QuantumCircuit,
    costCirc: QuantumCircuit,
    mixerCirc: QuantumCircuit,
    measure: bool = True,
) -> QuantumCircuit:
    """
    Construct the combined alternating circuit with Inital state, Cost Oprator, Mixer,
    and you also need to give a name to your circuit

    Args:
        n (int): the number of qubits, we will use it to generate classical circuit for
                measurement
        name (str): tell us what name you want to give your combined circuit
        simulator (Aer): give information of simulator
        p (int): the layer of circuit
        initCirc (QuantumCircuit): Initial state generator
        costCirc (QuantumCircuit): Cost Operator circuit
        mixerCirc (QuantumCircuit): Mixer

    Returns: the combined alternating circuit.
    """
    [initCirc, costCirc, mixerCirc], ancillas_num = ancilla_append(
        [initCirc, costCirc, mixerCirc]
    )
    circ = QAOAAnsatz(
        cost_operator=costCirc,
        reps=p,
        initial_state=initCirc,
        mixer_operator=mixerCirc,
        name=name,
    )  # the purpose of use this function, because this will alter the circuit parameter as gamma,beta dictionary

    if measure:
        # exclude the ancilla qubits, but always put ancilla qubits at the end of the circuit
        main_qubit = circ.num_qubits - ancillas_num
        cr = ClassicalRegister(n, "c")
        circ.add_register(cr)
        circ.measure(circ.qubits[0:main_qubit][::-1], cr)
        # [::-1] Change the order of qubits to match the order of the classical register

    circ = transpile(circ, simulator, optimization_level=0)

    return circ


def combGen(n: int, name: str, simulator: Aer, **circs):
    """
    combine general circuit
    p means how many circuit has been added
    """
    qn = QuantumRegister(n, "q")
    circ = QuantumCircuit(qn)
    circ.name = name
    for circsNo in circs:
        circ.append(circs[circsNo], qn[:])

    cr = ClassicalRegister(n, "c")
    circ.add_register(cr)
    circ.measure(circ.qubits[::-1], cr)
    # circ = transpile(circ, simulator, optimization_level=0)

    return circ


def bindParamGene(parameters: list, circ: QuantumCircuit, **kwargs) -> dict:
    """
    Convert a list of parameter to a dictionary, to show the relationship between variable parameters
    and their values.

    parameters: The input parameters.

    Return: The dictionary of parameters

    """

    param = {}
    for i, c in enumerate(circ.parameters):
        param[c] = float(parameters[i])

    return param


def simulate(
    circ: QuantumCircuit,
    simulator: Aer,
    parameters: Union[list, dict],
    numIter: int,
    **kwargs
) -> dict:
    """
    Run quantum circuit generated by combCirc <numIter> and obtain the vector Psi(gamma, beta)

    parameters: Parameters of the quantum circuit, gamma (parameters of U_C), beta (parameters of U_B).

    numIter: The number of iterations.
    and the function also receive any other
    Return: All <numIter> measurement result of the state vector.


    """
    if not isinstance(
        parameters, dict
    ):  # if you drop some list parameters, from initParamGen direcly
        parameters = bindParamGene(parameters=parameters, circ=circ)

    paraCirc = circ.assign_parameters(parameters)
    # paraCirc = transpile(paraCirc, simulator, optimization_level=0)
    # With different backend the circuit must be transpiled to corresonding gate else the back end could not run it properly
    # qObj = assemble(paraCirc, shots=numIter)  # a standard way to generate an experiment
    results = simulator.run(paraCirc, shots=numIter).result()
    rc = results.get_counts()

    return rc


def ancilla_append(circuits: List):
    """Ensure that circuits have the same number of qubits by adding ancilla qubits to the circuit with fewer qubits.

    Args:
        circuits (List): List of circuits to be compared.

    Returns:
        circuits (List): The updated list of circuits with the same number of qubits.
        max_ancillas (int): the number of ancilla qubits
    """
    # Determine the number of qubits in each circuit

    max_ancillas = 0
    max_name = ""
    for i, circ in enumerate(circuits):
        num_ancillas = circ.num_ancillas
        if num_ancillas > max_ancillas:
            max_ancillas = num_ancillas
            for reg in circ.qregs + circ.cregs:
                if isinstance(reg, AncillaRegister):
                    max_name = reg.name
                    break

    # Determine the difference in the number of qubits
    # Iterate through each circuit and add ancilla qubits if necessary
    for circ in circuits:
        num_ancillas = circ.num_ancillas
        if num_ancillas < max_ancillas:
            # Find the ancilla register in the circuit
            for reg in circ.qregs + circ.cregs:
                if isinstance(reg, AncillaRegister):
                    ancilla_register_name = reg.name
                    # Add the required number of ancilla qubits if existing ancilla register is not large enough
                else:
                    ancilla_register_name = max_name
                    # If no ancilla register exists, create a new one with the name of the maximum number of ancilla qubits

            circ.add_register(
                AncillaRegister(max_ancillas - num_ancillas, ancilla_register_name)
            )

    return circuits, max_ancillas
